// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: devices.sql

package database

import (
	"context"
	"database/sql"
)

const getAllTempSamples = `-- name: GetAllTempSamples :many
SELECT id, timestamp, sensor_type, sensor_number, fan_on, temperature, heater_power
FROM temp_samples
`

func (q *Queries) GetAllTempSamples(ctx context.Context) ([]TempSample, error) {
	rows, err := q.db.QueryContext(ctx, getAllTempSamples)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TempSample
	for rows.Next() {
		var i TempSample
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.SensorType,
			&i.SensorNumber,
			&i.FanOn,
			&i.Temperature,
			&i.HeaterPower,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTempSampleByID = `-- name: GetTempSampleByID :one
SELECT id, timestamp, sensor_type, sensor_number, fan_on, temperature, heater_power
FROM temp_samples
WHERE id = ?
`

func (q *Queries) GetTempSampleByID(ctx context.Context, id int64) (TempSample, error) {
	row := q.db.QueryRowContext(ctx, getTempSampleByID, id)
	var i TempSample
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.SensorType,
		&i.SensorNumber,
		&i.FanOn,
		&i.Temperature,
		&i.HeaterPower,
	)
	return i, err
}

const insertTempSample = `-- name: InsertTempSample :execresult
INSERT INTO temp_samples (
    timestamp, sensor_type, sensor_number, fan_on, temperature, heater_power
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertTempSampleParams struct {
	Timestamp    string  `json:"timestamp"`
	SensorType   string  `json:"sensor_type"`
	SensorNumber int64   `json:"sensor_number"`
	FanOn        bool    `json:"fan_on"`
	Temperature  float64 `json:"temperature"`
	HeaterPower  float64 `json:"heater_power"`
}

func (q *Queries) InsertTempSample(ctx context.Context, arg InsertTempSampleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertTempSample,
		arg.Timestamp,
		arg.SensorType,
		arg.SensorNumber,
		arg.FanOn,
		arg.Temperature,
		arg.HeaterPower,
	)
}

const insertTempSampleAnomaly = `-- name: InsertTempSampleAnomaly :exec
INSERT INTO temp_sample_anomalies (
    temp_sample_id, anomaly_label, created_at
) VALUES (?, ?, ?)
`

type InsertTempSampleAnomalyParams struct {
	TempSampleID int64  `json:"temp_sample_id"`
	AnomalyLabel string `json:"anomaly_label"`
	CreatedAt    string `json:"created_at"`
}

func (q *Queries) InsertTempSampleAnomaly(ctx context.Context, arg InsertTempSampleAnomalyParams) error {
	_, err := q.db.ExecContext(ctx, insertTempSampleAnomaly, arg.TempSampleID, arg.AnomalyLabel, arg.CreatedAt)
	return err
}
