// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: history_reports.sql

package database

import (
	"context"
)

const getReportSummarySinceUnix = `-- name: GetReportSummarySinceUnix :one
WITH
    temp_filtered AS (
        SELECT ts.id, ts.temperature
        FROM temp_samples ts
        WHERE unixepoch(ts.timestamp) >= CAST(?1 AS INTEGER)
    ),
    valve_filtered AS (
        SELECT vs.id, CASE WHEN vs.is_open THEN 1.0 ELSE 0.0 END AS open_rate
        FROM valve_samples vs
        WHERE unixepoch(vs.timestamp) >= CAST(?1 AS INTEGER)
    ),
    temp_alerts AS (
        SELECT COUNT(*) AS count
        FROM temp_sample_anomalies ta
        JOIN temp_samples ts ON ts.id = ta.temp_sample_id
        WHERE unixepoch(ts.timestamp) >= CAST(?1 AS INTEGER)
    ),
    valve_alerts AS (
        SELECT COUNT(*) AS count
        FROM valve_sample_anomalies va
        JOIN valve_samples vs ON vs.id = va.valve_sample_id
        WHERE unixepoch(vs.timestamp) >= CAST(?1 AS INTEGER)
    )
SELECT
    CAST(COALESCE((SELECT AVG(temperature) FROM temp_filtered), 0) AS REAL) AS avg_temp,
    CAST(COALESCE((SELECT MIN(temperature) FROM temp_filtered), 0) AS REAL) AS min_temp,
    CAST(COALESCE((SELECT MAX(temperature) FROM temp_filtered), 0) AS REAL) AS max_temp,
    CAST(COALESCE((SELECT AVG(open_rate) * 100.0 FROM valve_filtered), 0) AS REAL) AS avg_valve_open_rate,
    CAST(COALESCE((SELECT MIN(open_rate) * 100.0 FROM valve_filtered), 0) AS REAL) AS min_valve_open_rate,
    CAST(COALESCE((SELECT MAX(open_rate) * 100.0 FROM valve_filtered), 0) AS REAL) AS max_valve_open_rate,
    CAST((SELECT count FROM temp_alerts) + (SELECT count FROM valve_alerts) AS INTEGER) AS total_alerts,
    CAST((SELECT count FROM temp_alerts) AS INTEGER) AS temp_anomalies,
    CAST((SELECT count FROM valve_alerts) AS INTEGER) AS valve_anomalies
`

type GetReportSummarySinceUnixRow struct {
	AvgTemp          float64 `json:"avg_temp"`
	MinTemp          float64 `json:"min_temp"`
	MaxTemp          float64 `json:"max_temp"`
	AvgValveOpenRate float64 `json:"avg_valve_open_rate"`
	MinValveOpenRate float64 `json:"min_valve_open_rate"`
	MaxValveOpenRate float64 `json:"max_valve_open_rate"`
	TotalAlerts      int64   `json:"total_alerts"`
	TempAnomalies    int64   `json:"temp_anomalies"`
	ValveAnomalies   int64   `json:"valve_anomalies"`
}

func (q *Queries) GetReportSummarySinceUnix(ctx context.Context, sinceUnix int64) (GetReportSummarySinceUnixRow, error) {
	row := q.db.QueryRowContext(ctx, getReportSummarySinceUnix, sinceUnix)
	var i GetReportSummarySinceUnixRow
	err := row.Scan(
		&i.AvgTemp,
		&i.MinTemp,
		&i.MaxTemp,
		&i.AvgValveOpenRate,
		&i.MinValveOpenRate,
		&i.MaxValveOpenRate,
		&i.TotalAlerts,
		&i.TempAnomalies,
		&i.ValveAnomalies,
	)
	return i, err
}

const getTempHistorySinceUnix = `-- name: GetTempHistorySinceUnix :many
SELECT
    ts.id,
    ts.timestamp,
    ts.sensor_type,
    ts.sensor_number,
    ts.fan_on,
    ts.temperature,
    ts.heater_power,
    CAST(COALESCE(COUNT(ta.id), 0) AS INTEGER) AS alert_count,
    CAST(COALESCE(GROUP_CONCAT(ta.anomaly_label), '') AS TEXT) AS anomaly_labels
FROM temp_samples ts
LEFT JOIN temp_sample_anomalies ta ON ta.temp_sample_id = ts.id
WHERE unixepoch(ts.timestamp) >= CAST(?1 AS INTEGER)
GROUP BY ts.id
ORDER BY unixepoch(ts.timestamp) DESC
`

type GetTempHistorySinceUnixRow struct {
	ID            int64   `json:"id"`
	Timestamp     string  `json:"timestamp"`
	SensorType    string  `json:"sensor_type"`
	SensorNumber  int64   `json:"sensor_number"`
	FanOn         bool    `json:"fan_on"`
	Temperature   float64 `json:"temperature"`
	HeaterPower   float64 `json:"heater_power"`
	AlertCount    int64   `json:"alert_count"`
	AnomalyLabels string  `json:"anomaly_labels"`
}

func (q *Queries) GetTempHistorySinceUnix(ctx context.Context, sinceUnix int64) ([]GetTempHistorySinceUnixRow, error) {
	rows, err := q.db.QueryContext(ctx, getTempHistorySinceUnix, sinceUnix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTempHistorySinceUnixRow
	for rows.Next() {
		var i GetTempHistorySinceUnixRow
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.SensorType,
			&i.SensorNumber,
			&i.FanOn,
			&i.Temperature,
			&i.HeaterPower,
			&i.AlertCount,
			&i.AnomalyLabels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValveHistorySinceUnix = `-- name: GetValveHistorySinceUnix :many
SELECT
    vs.id,
    vs.timestamp,
    vs.sensor_type,
    vs.valve_number,
    vs.is_open,
    vs.flow_rate,
    CAST(COALESCE(COUNT(va.id), 0) AS INTEGER) AS alert_count,
    CAST(COALESCE(GROUP_CONCAT(va.anomaly_label), '') AS TEXT) AS anomaly_labels
FROM valve_samples vs
LEFT JOIN valve_sample_anomalies va ON va.valve_sample_id = vs.id
WHERE unixepoch(vs.timestamp) >= CAST(?1 AS INTEGER)
GROUP BY vs.id
ORDER BY unixepoch(vs.timestamp) DESC
`

type GetValveHistorySinceUnixRow struct {
	ID            int64   `json:"id"`
	Timestamp     string  `json:"timestamp"`
	SensorType    string  `json:"sensor_type"`
	ValveNumber   int64   `json:"valve_number"`
	IsOpen        bool    `json:"is_open"`
	FlowRate      float64 `json:"flow_rate"`
	AlertCount    int64   `json:"alert_count"`
	AnomalyLabels string  `json:"anomaly_labels"`
}

func (q *Queries) GetValveHistorySinceUnix(ctx context.Context, sinceUnix int64) ([]GetValveHistorySinceUnixRow, error) {
	rows, err := q.db.QueryContext(ctx, getValveHistorySinceUnix, sinceUnix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetValveHistorySinceUnixRow
	for rows.Next() {
		var i GetValveHistorySinceUnixRow
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.SensorType,
			&i.ValveNumber,
			&i.IsOpen,
			&i.FlowRate,
			&i.AlertCount,
			&i.AnomalyLabels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
