// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

type TempSample struct {
	ID           int64   `json:"id"`
	Timestamp    int64   `json:"timestamp"`
	SensorType   string  `json:"sensor_type"`
	SensorNumber int64   `json:"sensor_number"`
	FanOn        bool    `json:"fan_on"`
	Temperature  float64 `json:"temperature"`
	HeaterPower  float64 `json:"heater_power"`
}

type TempSampleAnomaly struct {
	ID           int64  `json:"id"`
	TempSampleID int64  `json:"temp_sample_id"`
	AnomalyLabel string `json:"anomaly_label"`
	CreatedAt    string `json:"created_at"`
}

type User struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ValveSample struct {
	ID          int64   `json:"id"`
	Timestamp   int64   `json:"timestamp"`
	SensorType  string  `json:"sensor_type"`
	ValveNumber int64   `json:"valve_number"`
	IsOpen      bool    `json:"is_open"`
	FlowRate    float64 `json:"flow_rate"`
}

type ValveSampleAnomaly struct {
	ID            int64  `json:"id"`
	ValveSampleID int64  `json:"valve_sample_id"`
	AnomalyLabel  string `json:"anomaly_label"`
	CreatedAt     string `json:"created_at"`
}
