// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type TempSample struct {
	ID           int64          `json:"id"`
	Timestamp    string         `json:"timestamp"`
	SensorType   string         `json:"sensor_type"`
	SensorNumber int64          `json:"sensor_number"`
	FanOn        bool           `json:"fan_on"`
	Temperature  float64        `json:"temperature"`
	HeaterPower  float64        `json:"heater_power"`
	Anomalies    sql.NullString `json:"anomalies"`
}

type User struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
