// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUsers(ctx context.Context) error
	GetAllTempSamples(ctx context.Context) ([]TempSample, error)
	GetAllValveSamples(ctx context.Context) ([]ValveSample, error)
	GetReportSummaryBetweenUnix(ctx context.Context, arg GetReportSummaryBetweenUnixParams) (GetReportSummaryBetweenUnixRow, error)
	GetTempHistorySinceUnix(ctx context.Context, sinceUnix int64) ([]GetTempHistorySinceUnixRow, error)
	GetTempMachineHistorySinceUnix(ctx context.Context, arg GetTempMachineHistorySinceUnixParams) ([]GetTempMachineHistorySinceUnixRow, error)
	GetTempSampleByID(ctx context.Context, id int64) (TempSample, error)
	GetTempSampleCount(ctx context.Context) (int64, error)
	GetValveHistorySinceUnix(ctx context.Context, sinceUnix int64) ([]GetValveHistorySinceUnixRow, error)
	GetValveMachineHistorySinceUnix(ctx context.Context, arg GetValveMachineHistorySinceUnixParams) ([]GetValveMachineHistorySinceUnixRow, error)
	GetValveSampleByID(ctx context.Context, id int64) (ValveSample, error)
	GetValveSampleCount(ctx context.Context) (int64, error)
	InsertTempSample(ctx context.Context, arg InsertTempSampleParams) (sql.Result, error)
	InsertTempSampleAnomaly(ctx context.Context, arg InsertTempSampleAnomalyParams) error
	InsertValveSample(ctx context.Context, arg InsertValveSampleParams) (sql.Result, error)
	InsertValveSampleAnomaly(ctx context.Context, arg InsertValveSampleAnomalyParams) error
	LookupUser(ctx context.Context, username string) (User, error)
	LookupUserByID(ctx context.Context, id string) (User, error)
}

var _ Querier = (*Queries)(nil)
