// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUsers(ctx context.Context) error
	LookupUser(ctx context.Context, username string) (User, error)
	LookupUserByID(ctx context.Context, id string) (User, error)
}

var _ Querier = (*Queries)(nil)
