// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username)
VALUES (?, ?)
RETURNING id, username, created_at, updated_at
`

type CreateUserParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUsers)
	return err
}

const lookupUser = `-- name: LookupUser :one
SELECT id, username, created_at, updated_at
FROM users
WHERE username = ?
`

func (q *Queries) LookupUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, lookupUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lookupUserByID = `-- name: LookupUserByID :one
SELECT id, username, created_at, updated_at
FROM users
WHERE id = ?
`

func (q *Queries) LookupUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, lookupUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
