// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: valves.sql

package database

import (
	"context"
	"database/sql"
)

const getAllValveSamples = `-- name: GetAllValveSamples :many
SELECT id, service_name, machine_id, timestamp, sensor_type, valve_number, is_open, flow_rate
FROM valve_samples
`

func (q *Queries) GetAllValveSamples(ctx context.Context) ([]ValveSample, error) {
	rows, err := q.db.QueryContext(ctx, getAllValveSamples)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValveSample
	for rows.Next() {
		var i ValveSample
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.MachineID,
			&i.Timestamp,
			&i.SensorType,
			&i.ValveNumber,
			&i.IsOpen,
			&i.FlowRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValveSampleByID = `-- name: GetValveSampleByID :one
SELECT id, service_name, machine_id, timestamp, sensor_type, valve_number, is_open, flow_rate
FROM valve_samples
WHERE id = ?
`

func (q *Queries) GetValveSampleByID(ctx context.Context, id int64) (ValveSample, error) {
	row := q.db.QueryRowContext(ctx, getValveSampleByID, id)
	var i ValveSample
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.MachineID,
		&i.Timestamp,
		&i.SensorType,
		&i.ValveNumber,
		&i.IsOpen,
		&i.FlowRate,
	)
	return i, err
}

const getValveSampleCount = `-- name: GetValveSampleCount :one
SELECT COUNT(*) AS count
FROM valve_samples
`

func (q *Queries) GetValveSampleCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getValveSampleCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertValveSample = `-- name: InsertValveSample :execresult
INSERT INTO valve_samples (
    service_name, machine_id, timestamp, sensor_type, valve_number, is_open, flow_rate
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertValveSampleParams struct {
	ServiceName string  `json:"service_name"`
	MachineID   string  `json:"machine_id"`
	Timestamp   int64   `json:"timestamp"`
	SensorType  string  `json:"sensor_type"`
	ValveNumber int64   `json:"valve_number"`
	IsOpen      bool    `json:"is_open"`
	FlowRate    float64 `json:"flow_rate"`
}

func (q *Queries) InsertValveSample(ctx context.Context, arg InsertValveSampleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertValveSample,
		arg.ServiceName,
		arg.MachineID,
		arg.Timestamp,
		arg.SensorType,
		arg.ValveNumber,
		arg.IsOpen,
		arg.FlowRate,
	)
}

const insertValveSampleAnomaly = `-- name: InsertValveSampleAnomaly :exec
INSERT INTO valve_sample_anomalies (
    valve_sample_id, anomaly_label, created_at
) VALUES (?, ?, ?)
`

type InsertValveSampleAnomalyParams struct {
	ValveSampleID int64  `json:"valve_sample_id"`
	AnomalyLabel  string `json:"anomaly_label"`
	CreatedAt     string `json:"created_at"`
}

func (q *Queries) InsertValveSampleAnomaly(ctx context.Context, arg InsertValveSampleAnomalyParams) error {
	_, err := q.db.ExecContext(ctx, insertValveSampleAnomaly, arg.ValveSampleID, arg.AnomalyLabel, arg.CreatedAt)
	return err
}
